services:
  retro-ranker:
    image: retroranker:latest
    container_name: retroranker
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: retroranker-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/retroranker/data:/pb_data
      - ./volumes/retroranker/public:/pb_public
      - ./volumes/retroranker/hooks:/pb_hooks
    env_file:
      - .env