services:
  retro-ranker:
    image: retroranker:latest
    container_name: retroranker
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: retroranker-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/retroranker/data:/pb_data
      - ./volumes/retroranker/public:/pb_public
      - ./volumes/retroranker/hooks:/pb_hooks
    env_file:
      - .env

  # lgtm:
  #   image: docker.io/grafana/otel-lgtm:0.8.1
  #   container_name: lgtm
  #   ports:
  #     - "3000:3000"
  #     - "4317:4317"
  #     - "4318:4318"
  #   environment:
  #     - GF_PATHS_DATA=/data/grafana
  #   volumes:
  #     - ./volumes/lgtm/grafana:/data/grafana
  #     - ./volumes/lgtm/prometheus:/data/prometheus
  #     - ./volumes/lgtm/loki:/data/loki
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
