services:
  retro-ranker:
    image: retroranker:latest
    container_name: retroranker
    ports:
      - "8000:8000"
    env_file:
      - .env

  lgtm:
    image: docker.io/grafana/otel-lgtm:0.8.1
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      - GF_PATHS_DATA=/data/grafana
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki
    stdin_open: true
    tty: true
    restart: unless-stopped
