services:
  retro-ranker:
    image: retro-ranker:latest
    container_name: retro-ranker
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Constrain memory/CPU to protect the VPS from OOM (works without Swarm)
    # mem_limit: 1024m
    # cpus: 0.75

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: retroranker-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/retroranker/data:/pb_data
      - ./volumes/retroranker/public:/pb_public
      - ./volumes/retroranker/hooks:/pb_hooks
    env_file:
      - .env
