// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contact from "./routes/contact.tsx";
import * as $devices_name_ from "./routes/devices/[name].tsx";
import * as $devices_index from "./routes/devices/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $terms from "./routes/terms.tsx";
import * as $DesktopNav from "./islands/DesktopNav.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contact.tsx": $contact,
    "./routes/devices/[name].tsx": $devices_name_,
    "./routes/devices/index.tsx": $devices_index,
    "./routes/index.tsx": $index,
    "./routes/privacy.tsx": $privacy,
    "./routes/terms.tsx": $terms,
  },
  islands: {
    "./islands/DesktopNav.tsx": $DesktopNav,
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
