// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_devices_name_ from "./routes/api/devices/[name].ts";
import * as $api_devices_index from "./routes/api/devices/index.ts";
import * as $charts_index from "./routes/charts/index.tsx";
import * as $compare_index from "./routes/compare/index.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $devices_name_ from "./routes/devices/[name].tsx";
import * as $devices_index from "./routes/devices/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $terms from "./routes/terms.tsx";
import * as $LayoutSelector from "./islands/LayoutSelector.tsx";
import * as $buttons_ClipboardButton from "./islands/buttons/ClipboardButton.tsx";
import * as $buttons_CompareButton from "./islands/buttons/CompareButton.tsx";
import * as $buttons_ShareButton from "./islands/buttons/ShareButton.tsx";
import * as $charts_DevicesPerBrandBarChart from "./islands/charts/DevicesPerBrandBarChart.tsx";
import * as $charts_DevicesPerRankingBarChart from "./islands/charts/DevicesPerRankingBarChart.tsx";
import * as $charts_DevicesPerReleaseYearLineChart from "./islands/charts/DevicesPerReleaseYearLineChart.tsx";
import * as $charts_DevicesRadarChart from "./islands/charts/DevicesRadarChart.tsx";
import * as $charts_DevicesSimilarRadarChart from "./islands/charts/DevicesSimilarRadarChart.tsx";
import * as $charts_FreshChart from "./islands/charts/FreshChart.tsx";
import * as $forms_DeviceComparisonForm from "./islands/forms/DeviceComparisonForm.tsx";
import * as $forms_DeviceSearchForm from "./islands/forms/DeviceSearchForm.tsx";
import * as $navigation_Breadcrumb from "./islands/navigation/Breadcrumb.tsx";
import * as $navigation_DesktopNav from "./islands/navigation/DesktopNav.tsx";
import * as $navigation_MobileNav from "./islands/navigation/MobileNav.tsx";
import * as $navigation_Navbar from "./islands/navigation/Navbar.tsx";
import * as $navigation_ThemeSwitcher from "./islands/navigation/ThemeSwitcher.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/devices/[name].ts": $api_devices_name_,
    "./routes/api/devices/index.ts": $api_devices_index,
    "./routes/charts/index.tsx": $charts_index,
    "./routes/compare/index.tsx": $compare_index,
    "./routes/contact.tsx": $contact,
    "./routes/devices/[name].tsx": $devices_name_,
    "./routes/devices/index.tsx": $devices_index,
    "./routes/index.tsx": $index,
    "./routes/privacy.tsx": $privacy,
    "./routes/terms.tsx": $terms,
  },
  islands: {
    "./islands/LayoutSelector.tsx": $LayoutSelector,
    "./islands/buttons/ClipboardButton.tsx": $buttons_ClipboardButton,
    "./islands/buttons/CompareButton.tsx": $buttons_CompareButton,
    "./islands/buttons/ShareButton.tsx": $buttons_ShareButton,
    "./islands/charts/DevicesPerBrandBarChart.tsx":
      $charts_DevicesPerBrandBarChart,
    "./islands/charts/DevicesPerRankingBarChart.tsx":
      $charts_DevicesPerRankingBarChart,
    "./islands/charts/DevicesPerReleaseYearLineChart.tsx":
      $charts_DevicesPerReleaseYearLineChart,
    "./islands/charts/DevicesRadarChart.tsx": $charts_DevicesRadarChart,
    "./islands/charts/DevicesSimilarRadarChart.tsx":
      $charts_DevicesSimilarRadarChart,
    "./islands/charts/FreshChart.tsx": $charts_FreshChart,
    "./islands/forms/DeviceComparisonForm.tsx": $forms_DeviceComparisonForm,
    "./islands/forms/DeviceSearchForm.tsx": $forms_DeviceSearchForm,
    "./islands/navigation/Breadcrumb.tsx": $navigation_Breadcrumb,
    "./islands/navigation/DesktopNav.tsx": $navigation_DesktopNav,
    "./islands/navigation/MobileNav.tsx": $navigation_MobileNav,
    "./islands/navigation/Navbar.tsx": $navigation_Navbar,
    "./islands/navigation/ThemeSwitcher.tsx": $navigation_ThemeSwitcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
