name: 🦕 Deno Preview
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deno Deploy Preview
    environment:
      name: Preview
      url: ${{ steps.deno.outputs.url }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "deno install"

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        id: deno
        uses: denoland/deployctl@v1
        with:
          project: "rr-test"
          entrypoint: "main.ts"
          root: "."
