name: Deploy new Docker Image version

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Create version number variable
        run: |
          DATE=$(date +"%Y%m%d")
          COUNT=$(git rev-list --count --since=midnight HEAD)
          echo "VERSION=v$DATE.$COUNT" >> $GITHUB_ENV

      # - name: Set up QEMU for multi-arch
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nergy101/retro-ranker:latest
          platforms: linux/arm64
          build-args: VERSION=$VERSION

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Get Known Hosts value
        run: echo "KNOWN_HOSTS=$(ssh-keyscan -H ${{ secrets.SSH_HOST }})" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: ${{ env.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Pull and start docker image on VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/code/retroranker
            docker compose pull
            docker compose up -d
