name: 🌙 Nightly Safari Tests

on:
  schedule:
    # Run at 3 AM UTC every day (1 hour after main nightly tests)
    - cron: "0 3 * * *"
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: nightly-safari-tests
  cancel-in-progress: true

jobs:
  test-safari:
    name: Run Safari/WebKit Tests - ${{ matrix.browser }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - browser: "WebKit (Desktop)"
            project: "webkit"
            runner: "macos-latest"
            device: "Desktop Safari"
          - browser: "Safari Mobile"
            project: "webkit-mobile"
            runner: "macos-latest"
            device: "iPhone 12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: playwright/package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
            playwright/.cache
          key: ${{ runner.os }}-playwright-${{ matrix.project }}-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-${{ matrix.project }}-

      - name: Install Playwright dependencies
        working-directory: playwright
        run: npm ci

      - name: Install Playwright browsers (WebKit only)
        working-directory: playwright
        run: npx playwright install webkit
        if: steps.cache-playwright.outputs.cache-hit != 'true'

      - name: Create screenshots directory
        run: mkdir -p playwright/screenshots

      - name: Make test failure handler executable
        run: chmod +x playwright/test-failure-handler.sh

      - name: Run Safari/WebKit tests with failure handler
        working-directory: playwright
        run: |
          # Set environment variables for the test failure handler
          export CI=true
          export TEST_USER_NICKNAME="${{ secrets.TEST_USER_NICKNAME }}"
          export TEST_USER_PASSWORD="${{ secrets.TEST_USER_PASSWORD }}"
          export TEST_USER_2_NICKNAME="${{ secrets.TEST_USER_2_NICKNAME }}"
          export TEST_USER_2_PASSWORD="${{ secrets.TEST_USER_2_PASSWORD }}"

          # Run tests with specific project
          npx playwright test --project=${{ matrix.project }} || true

          # Run the failure handler to process results
          ./test-failure-handler.sh
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safari-test-results-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            playwright/test-results/
            playwright/playwright-report/
          retention-days: 30

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safari-screenshots-${{ matrix.browser }}-${{ github.run_number }}
          path: playwright/screenshots/
          retention-days: 30
