name: 🌙 Nightly Safari Tests

on:
  schedule:
    # Run at 3 AM UTC every day (1 hour after main nightly tests)
    - cron: "0 3 * * *"
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: nightly-safari-tests
  cancel-in-progress: true

jobs:
  test-safari:
    name: Run Safari/WebKit Tests - ${{ matrix.browser }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - browser: "WebKit (Desktop)"
            project: "webkit"
            runner: "macos-latest"
            device: "Desktop Safari"
          - browser: "Safari Mobile"
            project: "webkit-mobile"
            runner: "macos-latest"
            device: "iPhone 12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: playwright/package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
            playwright/.cache
          key: ${{ runner.os }}-playwright-${{ matrix.project }}-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-${{ matrix.project }}-

      - name: Install Playwright dependencies
        working-directory: playwright
        run: npm ci

      - name: Install Playwright browsers (WebKit only)
        working-directory: playwright
        run: npx playwright install webkit
        if: steps.cache-playwright.outputs.cache-hit != 'true'

      - name: Create screenshots directory
        run: mkdir -p playwright/screenshots

      - name: Make test failure handler executable
        run: chmod +x playwright/test-failure-handler.sh

      - name: Run Safari/WebKit tests with failure handler
        working-directory: playwright
        run: |
          # Set environment variables for the test failure handler
          export CI=true
          export TEST_USER_NICKNAME="${{ secrets.TEST_USER_NICKNAME }}"
          export TEST_USER_PASSWORD="${{ secrets.TEST_USER_PASSWORD }}"
          export TEST_USER_2_NICKNAME="${{ secrets.TEST_USER_2_NICKNAME }}"
          export TEST_USER_2_PASSWORD="${{ secrets.TEST_USER_2_PASSWORD }}"

          # Run tests with specific project
          npx playwright test --project=${{ matrix.project }} || true

          # Run the failure handler to process results
          ./test-failure-handler.sh
        continue-on-error: true

      - name: Analyze test results and generate summary
        working-directory: playwright
        run: |
          echo "📊 Test Results Summary for ${{ matrix.browser }} (${{ matrix.project }})"
          echo "=========================================="

          if [ -f "test-results.json" ]; then
            # Use jq to parse the JSON and extract test statistics
            if command -v jq &> /dev/null; then
              TOTAL=$(jq '.stats.total' test-results.json 2>/dev/null || echo '0')
              PASSED=$(jq '.stats.passed' test-results.json 2>/dev/null || echo '0')
              FAILED=$(jq '.stats.failed' test-results.json 2>/dev/null || echo '0')
              SKIPPED=$(jq '.stats.skipped' test-results.json 2>/dev/null || echo '0')

              echo "📈 Test Statistics:"
              echo "   Total tests: $TOTAL"
              echo "   Passed: $PASSED"
              echo "   Failed: $FAILED"
              echo "   Skipped: $SKIPPED"

              if [ "$FAILED" -eq 0 ]; then
                echo "✅ All tests passed for ${{ matrix.browser }}!"
                echo "::notice::All tests passed for ${{ matrix.browser }} (${{ matrix.project }})"
              else
                echo "❌ $FAILED test(s) failed for ${{ matrix.browser }}"
                echo "::error::$FAILED test(s) failed for ${{ matrix.browser }} (${{ matrix.project }})"

                # List failed test names if available
                echo "📋 Failed tests:"
                jq -r '.suites[] | select(.specs != null) | .specs[] | select(.tests != null) | .tests[] | select(.results[] | .status == "failed") | .title' test-results.json 2>/dev/null | head -5 | while read test; do
                  if [ -n "$test" ]; then
                    echo "   - $test"
                  fi
                done
              fi
            else
              echo "⚠️  jq not available, using basic parsing..."
              if grep -q '"failed":[1-9]' test-results.json 2>/dev/null; then
                echo "❌ Tests failed for ${{ matrix.browser }}"
                echo "::error::Tests failed for ${{ matrix.browser }} (${{ matrix.project }})"
              else
                echo "✅ All tests passed for ${{ matrix.browser }}!"
                echo "::notice::All tests passed for ${{ matrix.browser }} (${{ matrix.project }})"
              fi
            fi
          else
            echo "⚠️  No test-results.json found"
            echo "::warning::No test results found for ${{ matrix.browser }} (${{ matrix.project }})"
          fi

          echo "=========================================="

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safari-test-results-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            playwright/test-results/
            playwright/playwright-report/
          retention-days: 30

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safari-screenshots-${{ matrix.browser }}-${{ github.run_number }}
          path: playwright/screenshots/
          retention-days: 30
